name: Build in DevContainer
on:
  push:
  pull_request:

jobs:
  build:
    name: Build in DevContainer
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/nid-roid/playwright-hands-on-devcontainer
          cacheFrom: ghcr.io/nid-roid/playwright-hands-on-devcontainer
          runCmd: pnpm build
